"""add external_url to announcements

Revision ID: 7e00b3f22e71
Revises: 20251029_add_audit_logs
Create Date: 2025-10-29 21:35:56.886621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e00b3f22e71'
down_revision = '20251029_add_audit_logs'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('external_url')

    # ### end Alembic commands ###
